from parkview_codeparse import detectors


def test_is_test_by_basename():
    assert detectors.is_test("test_foo.py")
    assert detectors.is_test("foo_test.py")
    assert detectors.is_test("foo.test.ts")
    assert detectors.is_test("foo.spec.js")
    assert not detectors.is_test("foo.py")


def test_is_test_by_directory():
    assert detectors.is_test("tests/foo.py")
    assert detectors.is_test("a/b/__tests__/foo.ts")
    assert detectors.is_test("spec/widget.rb")
    assert not detectors.is_test("a/b/widget.rb")


def test_is_config():
    assert detectors.is_config("Dockerfile")
    assert detectors.is_config("pyproject.toml")
    assert detectors.is_config("foo.yaml")
    assert detectors.is_config("a/b/.eslintrc.json")
    assert not detectors.is_config("foo.py")


def test_is_generated_by_path():
    assert detectors.is_generated("src/__generated__/foo.ts")
    assert detectors.is_generated("dist/bundle.js")
    assert not detectors.is_generated("src/foo.ts")


def test_is_generated_by_banner():
    assert detectors.is_generated("foo.py", "# @generated by some tool\nx = 1")
    assert detectors.is_generated("foo.py", "# Code generated by protoc-gen\npackage x")
    assert detectors.is_generated("foo.py", "// DO NOT EDIT\nint x;")
    assert not detectors.is_generated("foo.py", "x = 1\n")
