"""Heuristics for classifying files as test / generated / config.

These are filename- and content-based, not language-aware. They give the
LLM-Wiki consumer a fast way to bucket files before deeper processing —
generated files probably aren't worth summarizing, tests are evidence of
what production code is *supposed* to do, configs anchor the deployment
shape of a project.

All checks are conservative; the cost of misclassifying generated code as
"production" is bigger LLM bills, while misclassifying production as
"generated" silently drops it from the wiki — so prefer false on both
flags when the signal is weak.
"""

from __future__ import annotations

import os
import re

# Filename patterns. We match on the basename (lowercase) and on path
# components separately so `tests/foo.py` and `foo_test.py` both fire.
_TEST_BASENAME = re.compile(
    r"(^test_|_test\.|\.test\.|^.+\.spec\.|^.+_spec\.|^test\..*|tests?$)",
    re.IGNORECASE,
)
_TEST_DIR_NAMES = frozenset(
    {
        "test",
        "tests",
        "__tests__",
        "spec",
        "specs",
        "testing",
    }
)

_CONFIG_BASENAMES = frozenset(
    {
        "dockerfile",
        "makefile",
        "gnumakefile",
        "pyproject.toml",
        "setup.py",
        "setup.cfg",
        "package.json",
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "go.mod",
        "go.sum",
        "cargo.toml",
        "cargo.lock",
        "gemfile",
        "gemfile.lock",
        "rakefile",
        "tsconfig.json",
        "tslint.json",
        ".eslintrc.json",
        ".prettierrc",
        ".prettierrc.json",
        "vite.config.ts",
        "vite.config.js",
        "webpack.config.js",
        "rollup.config.js",
        "babel.config.js",
        "jest.config.js",
        "jest.config.ts",
        "tox.ini",
        "pytest.ini",
        "ruff.toml",
        "uv.lock",
        "poetry.lock",
        "pipfile",
        "pipfile.lock",
        "requirements.txt",
        "cmakelists.txt",
        ".gitignore",
        ".dockerignore",
    }
)
_CONFIG_EXTENSIONS = frozenset(
    {
        "toml",
        "yaml",
        "yml",
        "ini",
        "cfg",
        "conf",
        "env",
        "properties",
        "tf",
        "tfvars",
    }
)

_GENERATED_HEAD_PATTERNS = (
    re.compile(r"@?generated", re.IGNORECASE),
    re.compile(r"do not (modify|edit|change)", re.IGNORECASE),
    re.compile(r"this file is automatically generated", re.IGNORECASE),
    re.compile(r"autogenerated", re.IGNORECASE),
    re.compile(r"code generated by", re.IGNORECASE),
)
_GENERATED_PATH_HINTS = ("/generated/", "/__generated__/", "/dist/", "/build/")


def _basename_lower(path: str) -> str:
    return os.path.basename(path).lower()


def is_test(path: str) -> bool:
    if not path:
        return False
    name = _basename_lower(path)
    if _TEST_BASENAME.search(name):
        return True
    parts = path.replace("\\", "/").lower().split("/")
    return any(part in _TEST_DIR_NAMES for part in parts[:-1])


def is_config(path: str) -> bool:
    if not path:
        return False
    name = _basename_lower(path)
    if name in _CONFIG_BASENAMES:
        return True
    if "." in name:
        ext = name.rsplit(".", 1)[1]
        if ext in _CONFIG_EXTENSIONS:
            return True
    return False


def is_generated(path: str, content: str = "") -> bool:
    """A file is "generated" if its path or top-of-file says so.

    We only look at the first ~2 KB of content — generators always put the
    "do not edit" banner near the top.
    """
    if path:
        normalized = "/" + path.replace("\\", "/").lstrip("/").lower() + "/"
        if any(hint in normalized for hint in _GENERATED_PATH_HINTS):
            return True
    if content:
        head = content[:2048]
        for pat in _GENERATED_HEAD_PATTERNS:
            if pat.search(head):
                return True
    return False
